apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: "usuarios-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: "http://usuarios-service:8080"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: "Path=/api/usuarios/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: "pedidos-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: "http://pedidos-service:8080"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: "Path=/api/pedidos/**"
